In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import csv
import time
import chardet
import time

In [50]:
API_KEY = "MPA5HD9SWCXKHC7G7QTS"


SERVICES ={
    "161Y005": "BBHS00",           # M2              2달 지연
    "901Y014": "1080000",          # KOSPI_평균       2달 지연
    "901Y062": "P63AD",            # 주택매매가격지수(KB),총지수(서울)   1달 지연
    "901Y063": "P64AD",            # 주택전세가격지수(KB),총지수(서울)   1달 지연
    "731Y004": "0000001",          # 환율, 원/미국달러(매매기준율)       1달 지연
#    "405Y006": "*A"                # 국내공급물가지수 데이터부족으로 제외
}


start_date = "202406"
end_date = "202604"


file_name = f"서울은행_글로발변수_월단위_{start_date}_{end_date}.csv"

#BASE_URL = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/418/{SERVICE}/M/202301/202604"

In [51]:
# 갯수 확인
#
# for service in SERVICES:
#
#     # 길이 확인하기 위해서 1개만
#     one_url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1/{service}/M/202401/202604"
#
#     response = requests.get(one_url)
#
#     data = response.json()
#
#     body = data["StatisticSearch"]
#
#     list_total_count = body["list_total_count"]
#     print(f"list_total_count={list_total_count}")
#
#     time.sleep(3)
#
#     #
#     # 전체
#     #
#     all_url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/{list_total_count}/{service}/M/202401/202604"
#
#
#     print(all_url)
#
#     response = requests.get(all_url)
#
#     data = response.json()
#
#     data_df = pd.DataFrame(body["row"])
#
#
#
#     filter_df = data_df[data_df["ITEM_CODE1"] == SERVICES[service]]
#
#     print("---------------------")
#     print(f"service: {service}, code: {SERVICES[service]}")
#     print(data_df.head(10))
#     print(filter_df)
#     print(f"data name : {filter_df.iloc[0]['STAT_NAME']} {filter_df.iloc[0]['ITEM_NAME1']}")
#
#
#     time.sleep(3)

In [52]:
# 전체를 일기


SERVICE = "161Y005"
ITEM = SERVICES[SERVICE]

url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/{SERVICE}/M/{start_date}/{end_date}"

print(url)

response = requests.get(url)

data = response.json()

body = data["StatisticSearch"]

rows = body["row"]


df = pd.DataFrame(rows)

# ITEM_CODE1 == BBHS00 필터
total_df = df[df["ITEM_CODE1"] == ITEM]

m2_df = total_df.rename(columns={"DATA_VALUE":"M2"})[["TIME","M2"]]

# m2_total_df[["TIME","ITEM_CODE1","DATA_VALUE"]].to_csv(
#      file_name,
#      index=False,
#      encoding="utf-8-sig"
# )



print(len(m2_df))
m2_df.head(2)

https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/161Y005/M/202406/202604
22

      TIME         M2
0   202406  3811231.6
11  202407  3823839.5

In [53]:
# 전체를 일기


SERVICE = "901Y014"
ITEM = SERVICES[SERVICE]

url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/{SERVICE}/M/{start_date}/{end_date}"

print(url)

response = requests.get(url)

data = response.json()

body = data["StatisticSearch"]

rows = body["row"]


df = pd.DataFrame(rows)


total_df = df[df["ITEM_CODE1"] == ITEM]

kopsi_df = total_df.rename(columns={"DATA_VALUE":"KOSPI"})[["TIME","KOSPI"]]

# m2_total_df[["TIME","ITEM_CODE1","DATA_VALUE"]].to_csv(
#      file_name,
#      index=False,
#      encoding="utf-8-sig"
# )



print(len(kopsi_df))
kopsi_df.head(2)

https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/901Y014/M/202406/202604
22

      TIME    KOSPI
9   202406  2748.16
33  202407  2809.19

In [54]:
merge_df = pd.merge(m2_df,kopsi_df,on="TIME", how="outer")


print(len(merge_df))
merge_df.head(2)

22

     TIME         M2    KOSPI
0  202406  3811231.6  2748.16
1  202407  3823839.5  2809.19

In [55]:
# 전체를 일기


SERVICE = "901Y062"
ITEM = SERVICES[SERVICE]

url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/{SERVICE}/M/{start_date}/{end_date}"

print(url)

response = requests.get(url)

data = response.json()

body = data["StatisticSearch"]

rows = body["row"]


df = pd.DataFrame(rows)


total_df = df[df["ITEM_CODE1"] == ITEM]

house_sale_df = total_df.rename(columns={"DATA_VALUE":"HOUSE_SALE"})[["TIME","HOUSE_SALE"]]

# m2_total_df[["TIME","ITEM_CODE1","DATA_VALUE"]].to_csv(
#      file_name,
#      index=False,
#      encoding="utf-8-sig"
# )



print(len(house_sale_df))
house_sale_df.head(2)

https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/901Y062/M/202406/202604
23

      TIME HOUSE_SALE
5   202406     90.612
11  202407     90.996

In [56]:
merge_df = pd.merge(merge_df,house_sale_df,on="TIME", how="outer")


print(len(merge_df))
merge_df.head(2)

23

     TIME         M2    KOSPI HOUSE_SALE
0  202406  3811231.6  2748.16     90.612
1  202407  3823839.5  2809.19     90.996

In [57]:
# 전체를 일기


SERVICE = "901Y063"
ITEM = SERVICES[SERVICE]

url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/{SERVICE}/M/{start_date}/{end_date}"

print(url)

response = requests.get(url)

data = response.json()

body = data["StatisticSearch"]

rows = body["row"]


df = pd.DataFrame(rows)


total_df = df[df["ITEM_CODE1"] == ITEM]

rent_sale_df = total_df.rename(columns={"DATA_VALUE":"RENT_SALE"})[["TIME","RENT_SALE"]]

# m2_total_df[["TIME","ITEM_CODE1","DATA_VALUE"]].to_csv(
#      file_name,
#      index=False,
#      encoding="utf-8-sig"
# )



print(len(rent_sale_df))
rent_sale_df.head(2)

https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/901Y063/M/202406/202604
23

      TIME RENT_SALE
5   202406    95.144
11  202407    95.649

In [58]:
merge_df = pd.merge(merge_df,rent_sale_df,on="TIME", how="outer")


print(len(merge_df))
merge_df.head(2)

23

     TIME         M2    KOSPI HOUSE_SALE RENT_SALE
0  202406  3811231.6  2748.16     90.612    95.144
1  202407  3823839.5  2809.19     90.996    95.649

In [59]:
# 전체를 일기


SERVICE = "731Y004"
ITEM = SERVICES[SERVICE]

url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/3000/{SERVICE}/M/{start_date}/{end_date}"

print(url)

response = requests.get(url)

data = response.json()

body = data["StatisticSearch"]

rows = body["row"]


df = pd.DataFrame(rows)


total_df = df[(df["ITEM_CODE1"] == ITEM) & (df["ITEM_CODE2"] == "0000100")]

fx_df = total_df.rename(columns={"DATA_VALUE":"FX"})[["TIME","FX"]]

# m2_total_df[["TIME","ITEM_CODE1","DATA_VALUE"]].to_csv(
#      file_name,
#      index=False,
#      encoding="utf-8-sig"
# )



print(len(fx_df))
fx_df.head(2)

https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/3000/731Y004/M/202406/202604
23

      TIME       FX
0   202406  1380.13
86  202407  1383.38

In [60]:
merge_df = pd.merge(merge_df,fx_df,on="TIME", how="outer")


print(len(merge_df))
merge_df.head(2)

23

     TIME         M2    KOSPI HOUSE_SALE RENT_SALE       FX
0  202406  3811231.6  2748.16     90.612    95.144  1380.13
1  202407  3823839.5  2809.19     90.996    95.649  1383.38

In [61]:
# # 물가쪽은 데이터가 부족하다
#
#
# SERVICE = "405Y006"
# ITEM = SERVICES[SERVICE]
#
# url = f"https://ecos.bok.or.kr/api/StatisticSearch/MPA5HD9SWCXKHC7G7QTS/json/kr/1/1000/{SERVICE}/M/202401/202604"
#
# print(url)
#
# response = requests.get(url)
#
# data = response.json()
#
# body = data["StatisticSearch"]
#
# rows = body["row"]
#
#
# df = pd.DataFrame(rows)
#
#
# total_df = df[df["ITEM_CODE1"] == ITEM]
#
# price_df = total_df.rename(columns={"DATA_VALUE":"PRICE"})[["TIME","PRICE"]]
#
# # m2_total_df[["TIME","ITEM_CODE1","DATA_VALUE"]].to_csv(
# #      file_name,
# #      index=False,
# #      encoding="utf-8-sig"
# # )
#
#
#
# print(len(price_df))
# price_df.head(2)
#

In [62]:
# merge_df = pd.merge(merge_df,price_df,on="TIME", how="outer")
#
#
# print(len(merge_df))
# merge_df.head(2)

In [63]:

merge_df.to_csv(
     file_name,
     index=False,
     encoding="utf-8-sig"
)

In [64]:
# 결측 데이터 확인

with open(file_name, 'rb') as f:
    result = chardet.detect(f.read(10000))

print(file_name, result)

df = pd.read_csv(file_name)

print(df.isnull().sum())


#df.to_csv(file_name, index=False, encoding='utf-8-sig')

서울은행_글로발변수_월단위_202406_202604.csv {'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': 'eo', 'mime_type': 'text/plain'}
TIME          0
M2            1
KOSPI         1
HOUSE_SALE    0
RENT_SALE     0
FX            0
dtype: int64